name: General Issue
description: NOT a bug report.
title: "..."
labels: [ "triage" ]
assignees:
  - octocat
body:
  - type: textarea
    id: text
    attributes:
      label: Issue description
      description: Please describe the issue. Note that you can also use Discussions tab for general discussions.
      value: "..."
    validations:
      required: true